insert burgers (burger_name, devoured) values ("50/50 burger", TRUE);
insert burgers (burger_name, devoured) values ("Angus burger", FALSE);
insert burgers (burger_name, devoured) values ("Australasian hamburgers", TRUE);
insert burgers (burger_name, devoured) values ("Banquet burger", TRUE);
insert burgers (burger_name, devoured) values ("Barbecue burger", FALSE);
insert burgers (burger_name, devoured) values ("Bofsandwich", TRUE);
insert burgers (burger_name, devoured) values ("Butter burger", TRUE);
insert burgers (burger_name, devoured) values ("Buffalo burger", FALSE);
insert burgers (burger_name, devoured) values ("California burger", TRUE);
insert burgers (burger_name, devoured) values ("Carolina burger", FALSE);
insert burgers (burger_name, devoured) values ("Cheeseburger", TRUE);
insert burgers (burger_name, devoured) values ("Chili burger", TRUE);
insert burgers (burger_name, devoured) values ("Curry burger", TRUE);
insert burgers (burger_name, devoured) values ("Green chile burger", FALSE);
insert burgers (burger_name, devoured) values ("Hamdog", TRUE);
insert burgers (burger_name, devoured) values ("Hawaii burger", TRUE);
insert burgers (burger_name, devoured) values ("Jucy Lucy", FALSE);
insert burgers (burger_name, devoured) values ("Kimchi burger", TRUE);
insert burgers (burger_name, devoured) values ("Luther Burger", TRUE);
insert burgers (burger_name, devoured) values ("Naan burger", TRUE);
insert burgers (burger_name, devoured) values ("Pastrami Burger", FALSE);
insert burgers (burger_name, devoured) values ("Patty melt", TRUE);
insert burgers (burger_name, devoured) values ("Rice burger", TRUE);
insert burgers (burger_name, devoured) values ("Salmon burger", TRUE);
insert burgers (burger_name, devoured) values ("Slider", FALSE);
insert burgers (burger_name, devoured) values ("Slopper", TRUE);
insert burgers (burger_name, devoured) values ("Slugburger", FALSE);
insert burgers (burger_name, devoured) values ("Steak burger", TRUE);
insert burgers (burger_name, devoured) values ("Teriyaki burger", TRUE);
insert burgers (burger_name, devoured) values ("Veggie burger", FALSE);
